In [3]:
import torch
import torch.nn as nn

data = torch.Tensor([1, 2, 3])
softmax_function = nn.Softmax(dim=0)
output = softmax_function(data)
# assert round(output[0].item(), 2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

In [4]:
import torch
import torch.nn as nn

class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return torch.softmax(x, dim=0)

data = torch.Tensor([5, 2, 4])
my_softmax = MySoftmax()
output = my_softmax(data)
# assert round(output[-1].item(), 2) == 0.26
output


tensor([0.7054, 0.0351, 0.2595])

In [6]:
import torch
import torch.nn as nn

class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return torch.softmax(x, dim=0)

data = torch.Tensor([1, 2, 300000000])
my_softmax = MySoftmax()
output = my_softmax(data)
# assert round(output[0].item(), 2) == 0.0
output


tensor([0., 0., 1.])

In [7]:
import torch
import torch.nn as nn

class SoftmaxStable(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_max = torch.max(x, dim=0, keepdim=True)
        x_exp = torch.exp(x - x_max.values)
        partition = x_exp.sum(0, keepdim=True)
        return x_exp / partition

data = torch.Tensor([1, 2, 3])
softmax_stable = SoftmaxStable()
output = softmax_stable(data)
# assert round(output[-1].item(), 2) == 0.67
output

tensor([0.0900, 0.2447, 0.6652])

In [21]:
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name:str, yob:int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Student(Person):
    def __init__(self, name:str, yob:int, grade:int):
        super().__init__(name, yob)
        self._grade = grade

    def describe(self):
        print(f"Student - Name: {self._name}, yob: {self._yob}, grade: {self._grade}")

student1 = Student(name="studentZ2023", yob=2011, grade=6)
assert student1._yob == 2011
student1.describe()

Student - Name: studentZ2023, yob: 2011, grade: 6


In [20]:
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name:str, yob:int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Teacher(Person):
    def __init__(self, name:str, yob:int, subject:str):
        super().__init__(name, yob)
        self._subject = subject

    def describe(self):
        print(f"Teacher - Name: {self._name}, yob: {self._yob}, subject: {self._subject}")

teacher1 = Teacher(name="teacherZ2023", yob=1991, subject="History")
assert teacher1._yob == 1991
teacher1.describe()

Teacher - Name: teacherZ2023, yob: 1991, subject: History


In [18]:
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name:str, yob:int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Doctor(Person):
    def __init__(self, name:str, yob:int, speciality:str):
        super().__init__(name, yob)
        self._speciality = speciality

    def describe(self):
        print(f"Doctor - Name: {self._name}, yob: {self._yob}, speciality: {self._speciality}")

doctor1 = Doctor(name="doctorZ2023", yob=1981, speciality="Neurology")
# assert doctor1._yob == 1981
doctor1.describe()

Doctor - Name: doctorZ2023, yob: 1981, speciality: Neurology


In [25]:
class Ward:
    def __init__(self, name:str):
        self.__name = name
        self.__listPeople = list()

    def add_person(self, person: Person):
        self.__listPeople.append(person)

    def describe(self):
        print(f"Ward Name: {self.__name}")
        for p in self.__listPeople:
            p.describe()

    def count_doctor(self):
        count = 0
        for p in self.__listPeople:
            if isinstance(p, Doctor):
                count += 1
        return count

student1 = Student(name="studentA", yob=2010, grade=7)
teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
teacher2 = Teacher(name="teacherB", yob=1995, subject="History")
doctor1 = Doctor(name="doctorA", yob=1945, speciality="Endocrinologists")
doctor2 = Doctor(name="doctorB", yob=1975, speciality="Cardiologists")
ward1 = Ward(name="ward1")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)
ward1.count_doctor()


2

In [26]:
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_full(self):
        return len(self.__stack) == self.__capacity

    def push(self, value):
        if self.is_full():
            raise Exception("Stack is full")
        self.__stack.append(value)

stack1 = MyStack(capacity=5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print(stack1.is_full())

False


In [27]:
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_full(self):
        return len(self.__stack) == self.__capacity

    def push(self, value):
        if self.is_full():
            raise Exception("Stack is full")
        self.__stack.append(value)

    def top(self):
        if self.is_full():
            raise Exception("Stack is full")
        return self.__stack[-1]

stack1 = MyStack(capacity=5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print(stack1.top())

2


In [28]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def is_full(self):
        return len(self.__queue) == self.__capacity

    def enqueue(self, value):
        if self.is_full():
            raise Exception("Queue is full")
        self.__queue.append(value)

queue1 = MyQueue(capacity=5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print(queue1.is_full())

False


In [29]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def is_empty(self):
        return len(self.__queue) == 0

    def is_full(self):
        return len(self.__queue) == self.__capacity

    def dequeue(self):
        if self.is_empty():
            raise Exception("Queue is empty")
        return self.__queue.pop(0)

    def enqueue(self, value):
        if self.is_full():
            raise Exception("Queue is full")
        self.__queue.append(value)

    def front(self):
        if self.is_empty():
            raise Exception("Queue is empty")
        return self.__queue[0]

queue1 = MyQueue(capacity=5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print(queue1.front())

1
